### ISSUE TITLE
Descrever os critérios de aceitação para cada user story

### ISSUE THREAD

**Issue by sabrinaberno** [mdsreq-fga-unb/2024.1-Crystaleum-2#11]
Atualmente, não estão descritos os critérios de aceitação para as user stories, o que é crucial para garantir que as funcionalidades atendam aos requisitos esperados.

**Problemas Identificados:**
- Ausência de critérios de aceitação torna difícil a validação das funcionalidades durante a fase de testes.

**Comment by antonioleaojr** [comment]
resolvido por @pedroyen21:  https://github.com/mdsreq-fga-unb/2024.1-Crystaleum-2/commit/0da3c4697aea6b8610a85e6889ae834ec105a32a
