### ISSUE TITLE
PBB

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-Crystaleum-2#16]
- [ ] visualmente a estrutura do canvas não está correta
- [ ] as personas devem estar uma ao lado da outra, e não, uma em cima e outra embaixo
- [ ] as features estão desorganizadas por falta de posicionamento correto das personas 
- [ ] o COORG deve ser aplicado dentro do canvas e não em um material a parte
- [ ] não foram identificados os BDDs

**Comment by pedroyen21** [comment]
Backlog corrigido: https://mdsreq-fga-unb.github.io/2024.1-Crystaleum-2/missao4/correcoes-missao3/pbb/
