### ISSUE TITLE
Separar requisitos funcionais e não funcionais em tabelas diferentes

### ISSUE THREAD

**Issue by sabrinaberno** [mdsreq-fga-unb/2024.1-Crystaleum-2#9]
Atualmente, os requisitos funcionais (RF) e não funcionais (RNF) estão misturados na mesma tabela. Para melhorar a organização e clareza da documentação, é necessário separá-los em tabelas distintas.

**Problemas Identificados:**
A mistura de requisitos funcionais e não funcionais em uma única tabela dificulta a visualização e compreensão das especificações.

**Solução Proposta:**
- [ ] Criar uma tabela separada para os requisitos funcionais (RF).
- [ ] Criar uma tabela separada para os requisitos não funcionais (RNF).

**Comment by pedroyen21** [comment]
Requisitos separados: https://mdsreq-fga-unb.github.io/2024.1-Crystaleum-2/missao2/backlog/
